export const BACK_TO_LIST_PAGE_ACTION = 'BACK_TO_LIST_PAGE_ACTION';
export const ADD_NEW_FORM_CONFIG_PAGE_ACTION = 'ADD_NEW_FORM_CONFIG_PAGE_ACTION';
export const EDIT_FORM_CONFIG_PAGE_ACTION = 'EDIT_FORM_CONFIG_PAGE_ACTION';

export const SHOW_POPUP_WINDOW_ACTION = 'SHOW_POPUP_WINDOW_ACTION';
export const HIDE_POPUP_WINDOW_ACTION = 'HIDE_POPUP_WINDOW_ACTION';

export const DELETE_FORM_CONFIG_ACTION = 'DELETE_FORM_ACTION';

export const ADD_FORM_ACTION = 'ADD_FORM_ACTION';
export const EDIT_FORM_ACTION = 'EDIT_FORM_ACTION';

export const ADD_FORM_FIELDSET_ACTION = 'ADD_FORM_FIELDSET_ACTION';
export const CLEAR_FORM_CONFIG_MATRIX_ACTION = 'CLEAR_FORM_CONFIG_MATRIX_ACTION';

export const DELETE_FORM_FIELDSET_ACTION = 'DELETE_FORM_FIELDSET_ACTION';
export const EDIT_FORM_FIELDSET_ACTION = 'EDIT_FORM_FIELDSET_ACTION';

export const DELETE_FORM_FIELD_ACTION = 'DELETE_FORM_FIELD_ACTION';
export const ADD_FORM_FIELD_ACTION = 'ADD_FORM_FIELD_ACTION';
export const EDIT_FORM_FIELD_ACTION = 'EDIT_FORM_FIELD_ACTION';
export const CLEAR_FIELD_CONFIG_MATRIX_ACTION = 'CLEAR_FIELD_CONFIG_MATRIX_ACTION';